--- 
schemaVersion: str()
adminCode: str()
releases: 
  - 
    contact: 
      email: str()
    date: 
      created: str()
      metadataLastUpdated: str()
    description: 
      en: str()
      fr: str()
    name: 
      en: str()
      fr: str()
    licenses:
      - 
        URL: 
          en: str()
          fr: str()
        spdxID: str()
    repositoryURL: 
      en: str()
      fr: str()
    tags: 
      en:
        - str()
      fr: 
        - str()
